# Generated by Django 4.1.5 on 2023-01-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0005_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_read',
        ),
    ]
