# Generated by Django 4.1.5 on 2023-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0006_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
