# Generated by Django 4.1.5 on 2023-02-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0008_customshelfstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshelfstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='book', to='api_books.book'),
        ),
        migrations.AlterField(
            model_name='customshelfstatus',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shelf', to='api_books.book'),
        ),
    ]
