# Generated by Django 4.1.5 on 2023-02-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0010_alter_customshelfstatus_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshelfstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_books.book'),
        ),
        migrations.AlterField(
            model_name='customshelfstatus',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_books.shelf'),
        ),
    ]
